version: "3.8"
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data # Lưu data bền vững
    ports:
      - "5432:5432"

  backend:
    # Pull image từ Docker Hub (do CI/CD đẩy lên)
    image: username-dockerhub/finance-backend:latest
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      PORT: 4000
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "4000:4000"

  frontend:
    # Pull image từ Docker Hub
    image: username-dockerhub/finance-frontend:latest
    restart: always
    ports:
      - "80:80" # Chạy cổng 80 (HTTP)

volumes:
  pgdata: